on:
#   push:
#     branches: master
  workflow_dispatch:
  schedule:
    - cron: '0 */8 * * *'
name: Sync JihuLab Mirror
jobs:
  run:
    name: Sync JihuLab Mirror
    runs-on: ubuntu-latest
    steps:
#       - uses: styfle/cancel-workflow-action@0.9.0
#         with:
#           all_but_latest: true
#           access_token: ${{ github.token }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@jihulab.com:samiya/scoop-samiya.git
          ssh_private_key:
            ${{ secrets.JIHULAB_SSH_DEPLOY_KEY }}
